swap adaptor changes
bcnmy/hyphen-contract pull request #48
Opened 2022-05-21 16:47 UTC by divyaN73

2022-05-23 14:18 UTC, tomarsachin2271 commented on contracts/hyphen/swaps/UniswapAdaptor.sol
> +    // For this example, we will set the pool fee to 0.3%.
remove this comment.

2022-05-23 14:28 UTC, divyaN73 commented on contracts/hyphen/interfaces/ISwapAdaptor.sol
> +    function swap(
no need, as discussed

2022-05-24 02:33 UTC, ankurdubey521 requested changes

2022-05-24 02:33 UTC, ankurdubey521 commented on contracts/hyphen/swaps/UniswapAdaptor.sol
> +        SwapRequest[] memory swapRequests
use calldata instead of memory to save gas

2022-05-24 02:33 UTC, ankurdubey521 commented on contracts/hyphen/LiquidityPool.sol
> +    ) public tokenChecks(tokenAddress) whenNotPaused nonReentrant {
use external instead of public to save some gas

2022-05-24 02:33 UTC, ankurdubey521 commented on contracts/hyphen/LiquidityPool.sol
> +        for (uint256 index = 0; index < swapRequest.length; ++index) {
create a separate variable for swapRequest.length, and enclose the for loop inside unchecked {} to save gas

2022-05-24 02:33 UTC, ankurdubey521 commented on contracts/hyphen/LiquidityPool.sol
> +        SwapRequest[] memory swapRequest
use calldata instead of memory

2022-05-24 02:33 UTC, ankurdubey521 commented on contracts/hyphen/LiquidityPool.sol
> +        for (uint256 index = 0; index < swapRequest.length; ++index) {
create separate variable for swapRequest.length and wrap the whole loop in unchecked {} to save gas

2022-05-24 02:33 UTC, ankurdubey521 commented on contracts/hyphen/LiquidityPool.sol
> +        SwapRequest[] memory swapRequests,
use calldata

2022-05-24 02:33 UTC, ankurdubey521 commented on contracts/hyphen/LiquidityPool.sol
> +        string memory swapAdaptor
use calldata

2022-05-24 02:36 UTC, ankurdubey521 commented
We should also update [the Upgradibility Tests](https://github.com/bcnmy/hyphen-contract/blob/HP-60/test/Upgradibility.tests.ts) since we're upgrading the Liquidity Pool, but this not necessarily required at the moment

2022-05-24 12:35 UTC, ankurdubey521 approved these changes

2022-05-25 12:23 UTC, tomarsachin2271 commented on contracts/hyphen/swaps/UniswapAdaptor.sol
> +                require(index == 0 || swapRequests[index].operation != SwapOperation.ExactOutput, "Invalid swap request");
require(swapArrayLength == 1 || swapRequests[1].operation == SwapOperation.ExactInput, "Invalid swap operation")

2022-05-26 08:53 UTC, tomarsachin2271 commented on contracts/hyphen/swaps/UniswapAdaptor.sol
> +    address public immutable WRAPPER_ADDRESS;
Change name to NATIVE_WRAPPED_ADDRESS

2022-05-26 12:18 UTC, ankurdubey521 approved these changes

2022-05-26 12:29 UTC, merged